name: GH Pages Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"

  # pull_request:
  #   branches: [main]
  #   paths-ignore:
  #     - "docs/**"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v2

      - name: Install dependencies ðŸ”§
        run: make install

      - name: Build ðŸ—ï¸
        run: make build

      - name: Deploy to GitHub Pages ðŸš€
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book

  diff:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      output3: ${{ steps.step3.outputs.test }}
    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v2

      - id: step1
        shell: bash
        run: |
          git fetch origin main
          git diff origin/main..HEAD > mydiff
          echo "$mydiff"
          echo "$(git diff origin/main..HEAD)"
          echo "::set-output name=test::$(git diff origin/main..HEAD)"

      - id: step2
        run: echo "::set-output name=test::hello"

      - id: step3
        run: echo "::set-output name=test::world"

  send-to-discord:
    runs-on: ubuntu-latest
    needs: diff
    steps:
      - name: Echo
        run: |
          echo "DIFF ${{needs.diff.outputs.output1}} ${{needs.diff.outputs.output2}}"
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "HI ${{needs.diff.outputs.output1}} ${{needs.diff.outputs.output2}}"
          # content: "${{ github.event.head_commit.message }}\n\n```diff\nSome Code\n```"
